# Form implementation generated from reading ui file 'ui/new_project.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(344, 197)
        Dialog.setMinimumSize(QtCore.QSize(344, 197))
        icon = QtGui.QIcon.fromTheme("document-new")
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditName = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout.addWidget(self.lineEditName)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditDir = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditDir.setObjectName("lineEditDir")
        self.verticalLayout.addWidget(self.lineEditDir)
        self.pushButtonSelectDir = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonSelectDir.setObjectName("pushButtonSelectDir")
        self.verticalLayout.addWidget(self.pushButtonSelectDir)
        spacerItem = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.pushButtonSelectDir)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.Check) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.pushButtonSelectDir.clicked.connect(Dialog.selectDir) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create new project"))
        self.label_2.setText(_translate("Dialog", "Project Name"))
        self.label.setText(_translate("Dialog", "Project &dirctory"))
        self.pushButtonSelectDir.setText(_translate("Dialog", "Select"))
