# Form implementation generated from reading ui file 'ui/select_tag_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Select_tag(object):
    def setupUi(self, Select_tag):
        Select_tag.setObjectName("Select_tag")
        Select_tag.resize(535, 463)
        Select_tag.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Select_tag)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Select_tag)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=Select_tag)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxPLCFilter = QtWidgets.QComboBox(parent=Select_tag)
        self.comboBoxPLCFilter.setCurrentText("")
        self.comboBoxPLCFilter.setObjectName("comboBoxPLCFilter")
        self.gridLayout.addWidget(self.comboBoxPLCFilter, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(parent=Select_tag)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=Select_tag)
        self.label_2.setText("PLC")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditNameFilter = QtWidgets.QLineEdit(parent=Select_tag)
        self.lineEditNameFilter.setObjectName("lineEditNameFilter")
        self.gridLayout.addWidget(self.lineEditNameFilter, 2, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(parent=Select_tag)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 5, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Select_tag)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Select_tag)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 6, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(parent=Select_tag)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBoxTypeFilter = QtWidgets.QComboBox(parent=Select_tag)
        self.comboBoxTypeFilter.setObjectName("comboBoxTypeFilter")
        self.gridLayout.addWidget(self.comboBoxTypeFilter, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Select_tag)
        QtCore.QMetaObject.connectSlotsByName(Select_tag)

    def retranslateUi(self, Select_tag):
        _translate = QtCore.QCoreApplication.translate
        Select_tag.setWindowTitle(_translate("Select_tag", "Select Tag"))
        self.label.setText(_translate("Select_tag", "Select tag for ..."))
        self.label_3.setText(_translate("Select_tag", "Name Filter"))
        self.checkBox.setText(_translate("Select_tag", "Select Base Tag if possible"))
        self.label_4.setText(_translate("Select_tag", "Type Filter"))
