# Form implementation generated from reading ui file 'ui/FormTab2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormTabWidget(object):
    def setupUi(self, FormTabWidget):
        FormTabWidget.setObjectName("FormTabWidget")
        FormTabWidget.resize(638, 410)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormTabWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(parent=FormTabWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.pushButtonPlus = QtWidgets.QPushButton(parent=FormTabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pushButtonPlus.sizePolicy().hasHeightForWidth())
        self.pushButtonPlus.setSizePolicy(sizePolicy)
        self.pushButtonPlus.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButtonPlus.setIcon(icon)
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.gridLayout.addWidget(self.pushButtonPlus, 0, 1, 1, 1)
        self.radioButtonRead = QtWidgets.QRadioButton(parent=FormTabWidget)
        self.radioButtonRead.setObjectName("radioButtonRead")
        self.gridLayout.addWidget(self.radioButtonRead, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(FormTabWidget)
        QtCore.QMetaObject.connectSlotsByName(FormTabWidget)

    def retranslateUi(self, FormTabWidget):
        _translate = QtCore.QCoreApplication.translate
        FormTabWidget.setWindowTitle(_translate("FormTabWidget", "Form"))
        self.radioButtonRead.setText(_translate("FormTabWidget", "Read Periodicaly"))
