# Form implementation generated from reading ui file 'ui/FormTab.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormTabWidget(object):
    def setupUi(self, FormTabWidget):
        FormTabWidget.setObjectName("FormTabWidget")
        FormTabWidget.resize(529, 248)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormTabWidget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonsLayout = QtWidgets.QHBoxLayout()
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.verticalLayout.addLayout(self.ButtonsLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormTabWidget)
        QtCore.QMetaObject.connectSlotsByName(FormTabWidget)

    def retranslateUi(self, FormTabWidget):
        _translate = QtCore.QCoreApplication.translate
        FormTabWidget.setWindowTitle(_translate("FormTabWidget", "Form"))
